import { Router } from "express";
import authRoutes from "./auth.routes";
import eventRoutes from "./event.routes";
import adminEventRoutes from "./admin/event.routes";
import articleRoutes from "./article.routes";
import adminArticleRoutes from "./admin/article.routes";
import contactRoutes from "./contact.routes";
import adminContactRoutes from "./admin/contact.routes";
import serviceRoutes from "./service.routes";
import adminServiceRoutes from "./admin/service.routes";
import galleryRoutes from "./gallery.routes";
import adminGalleryRoutes from "./admin/gallery.routes";
import testimonialRoutes from "./testimonial.routes";
import adminTestimonialRoutes from "./admin/testimonial.routes";
import partnerRoutes from "./partner.routes";
import adminPartnerRoutes from "./admin/partner.routes";
import adminCompanyRoutes from "./admin/company.routes";
import jobRoutes from "./job.routes";
import adminJobRoutes from "./admin/job.routes";
import programCategoryRoutes from "./programCategory.routes";
import adminProgramCategoryRoutes from "./admin/programCategory.routes";
import programRoutes from "./program.routes";
import adminProgramRoutes from "./admin/program.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/events", eventRoutes);
router.use("/admin/events", adminEventRoutes);
router.use("/articles", articleRoutes);
router.use("/admin/articles", adminArticleRoutes);
router.use("/contact", contactRoutes);
router.use("/admin/contact-messages", adminContactRoutes);
router.use("/services", serviceRoutes);
router.use("/admin/services", adminServiceRoutes);
router.use("/gallery", galleryRoutes);
router.use("/admin/gallery", adminGalleryRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/admin/testimonials", adminTestimonialRoutes);
router.use("/partners", partnerRoutes);
router.use("/admin/partners", adminPartnerRoutes);
router.use("/admin/companies", adminCompanyRoutes);
router.use("/jobs", jobRoutes);
router.use("/admin/jobs", adminJobRoutes);
router.use("/program-categories", programCategoryRoutes);
router.use("/admin/program-categories", adminProgramCategoryRoutes);
router.use("/programs", programRoutes);
router.use("/admin/programs", adminProgramRoutes);

export default router;